### ISSUE TITLE
Base permission options

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#118]
The three current permission modes available: _Open Access_, _AIC_ and _Private_ should be reduced to two, and permissions changed according to the following:
- **AIC**
  - Owner: read, write, control (set permissions)
  - All logged in users: read 
- **Department**
  - Owner: read, write, control (set permissions)
  - Users in owner's department: read 

No "open access" option is provided.

**Comment by awead** [comment]
Private is the current "default" permission for any newly created asset. Given the above case, perhaps "Department" should be the default for newly created assets.

Note: Citi resources imported via Geneva have, in effect, and "open access" permission level because we don't apply permissions to them.

**Comment by scossu** [comment]
Agree. "Department" should be the default. 

Re: external resources: yes, it will be other Fedora clients' job to set up the webACs for the resources they ingest outside of Hydra.
