### ISSUE TITLE
Support preferred title or label

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#174]
Currently all titles go under dc:title. 

This ticket is to discuss and implement support for "preferred" and, implicitly or explicitly, "alternative" titles. 

There can be several solutions to this: 
1. Introduce a single-valued skos:prefLabel
   - Keep the current dc:title and migrate the contents to skos:prefLabel
   - Use dc:title for alternative titles from that point on 
   - This will need some disambiguation if users have already entered multiple titles
2. Same as above, but replace dc:title with rdfs:label for consistency
   - This requires overriding core Sufia methods and may require some care
   - This may not even be necessary: according to this document, rdfs:label is a subproperty of dc:title: http://dublincore.org/documents/dcq-rdf-xml/#tilab
3. Same as 1, but replace dc:title with skos:altLabel
   - I am not particularly in favor of this; implicitly assuming alternative titles using dc:title or rdfs:labels is simpler and more effective. No need to explicitly designate a title or label as alternate

In all three cases: 
- The human readable labels of the chosen properties should be "title", not "label" to avoid confusion with other uses of the name "label" within the museum
- Solr search for dc:title or rdfs:label should include results from skos:prefLabel

**Comment by scossu** [comment]
@acoburn , what are your thoughts about this?

**Comment by acoburn** [comment]
All of the options seem reasonable, but if it was up to me, I'd go with option 3. Here's why:

In general, I would be inclined to keep the different titles within the same namespace, meaning that if one is preferred while others are alternate, you'd use `skos:prefLabel` and `skos:altLabel` (option 3). Both properties are sub-properties of `rdfs:label`, so if you needed all the values from a triplestore, you could query for rdfs:label. That principle also applies to using `skos:prefLabel` with either `dc:title` or `rdfs:label` (options 1 & 2). The only advantage of option 3 is that from an ontological perspective, you can fall back on an explicit, defined relationship between `skos:prefLabel` and `skos:altLabel` (e.g. defined as pairwise disjoint properties in the skos ontology); otherwise, the relationship is more dependent on your own implemented application logic, which may not be clear to external sources, should you choose to make the data available.

**Comment by scossu** [comment]
Thanks for your comment. Option 3 may work if we follow the principle of being as specific as possible when cataloging, and as broad as possible when searching. I can see the advantage of separating prefLabel and altLabel in case we want to exclude preferred titles from a query (e.g. to place them in a separate area of the UI). 

All this will of course need  a store with RDFS reasoning capabilities, so while we don't have that available for LAKEshore, we may have to employ some Solr trickery to achieve similar results. That is why I was preferring option 1 in the short term (especially to avoid changing the references to dc:title in the application). Option 3 may be the ideal solution whenever a Solr over triplestore solution became available.

**Comment by acoburn** [comment]
I think you said it well: that option 3 is more of an ideal modeling scenario. In terms of simplicity of implementation, however, I can definitely see significant advantages to option 1.

**Comment by scossu** [comment]
Migrated to issue tracking system.
