### ISSUE TITLE
Permissions set in upload form are not retained

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#191]
If I set additional users and/or group permissions on an asset upload form, then go to the edit page for the asset, those additional permissions are not displayed. 

Department/AIC changes to default permissions are saved.

**Comment by awead** [comment]
I found a bug that was preventing additional user permissions from displaying, but otherwise this is working. What may be happening is that you're not clicking the "+" button that actually adds the permission to the form.

Also, because during upload the permissions are applied as a batch job to all files, when you are taken to the file listing page you may not immediately see the new permissions applied. Usually if you want a minute, the new permissions will appear.

**Comment by scossu** [comment]
I have repeated the process: 
- Log in as scossuadmin
- Upload image file
- Leave visibility to "Department" 
- Grant "rdoll" user edit access on upload metadata page
- Click on plus sign and verify that user is added to the permission list
- Grant "DEA" group view/download access on same page
- Click on plus sign and verify that group is added to the permission list
- Click "Save" 
- Verify that the asset is in "My Assets" list, clock icon is on it
- Wait a minute and reload the page until clock icon is gone
- Go to edit page for asset, permissions are only set for scossuadmin and Admin group. 

This happens if I log in as scossu as well.

**Comment by scossu** [comment]
This also occurs in batch edit (when selecting multiple items from My Assets and clicking on "Edit Selected").

**Comment by scossu** [comment]
This is only happening in production. Test behaves as expected in both upload and batch edit forms.

**Comment by awead** [comment]
@scossu prod doesn't have the latest code. Let me know if you want me to deploy it.

**Comment by scossu** [comment]
Yes please.
