### ISSUE TITLE
Display CITI resource page by passing resource type and CITI UID in URL

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-lakeshore#196]
Allow LAKEshore to display an individual non-asset page (Work, Actor, Exhibition, Transaction, Shipment) based on either of the following URL forms (this is flexible, depending on technical issues): 

```
 /<content_model>/relationships?citiUid=<citi_uid>

 /<content_model>/citiUid:<citi_uid>/relationships
```

Where:
- `content_model` is the LAKEhore content type as used in the view page URL (e.g. `works`)
- `citi_uid` is the value of the `aic:citiUid` property

**Comment by scossu** [comment]
This page should use a different, simplified template that displays only the asset list and the relationship links:

![lakeshore-nonasset-table-citi](https://cloud.githubusercontent.com/assets/4306733/12598734/b87fe1f2-c451-11e5-8acc-ec3351a2ba5c.png)

**Comment by awead** [comment]
@scossu I don't think this should present too much of a challenge. Although, I think the more RESTful uri would look like: `/<content_model>/<citi_id>/relationships`. I forget, is the CITI id the same as the Fedora one, or is it like WO-123456, for example, for works?

**Comment by scossu** [comment]
The CITI UID is, I believe, the one defined in https://github.com/aic-collections/aicdams-lakeshore/blob/master/app/models/citi_resource.rb#L10 (the "123456" in your example without "WO-"). 

I prefer explicitly indicating the property name (`citiUid`) in the URI because the CITI UID is not the unique identifier for the LAKE resource. It is an arbitrary property, so I don't think that that specific REST paradigm applies here. 

Keeping this scheme allows for potential expansion, e.g. display an asset by its `aic:legacyUid` attribute if we want. 

For the same reason, the content model has to be specified, because "123456" is unique within CITI Objects (Works) but not necessarily across all CITI resources.

**Comment by awead** [comment]
Then to do it that way would require more work. Since this would require searching, a better approach would be to pass any parameters to the catalog controller, `/catalog`, and have it render a different view. What's the background behind this use case? Why do you need a different display of relationships?

**Comment by scossu** [comment]
This page is meant to be displayed in CITI as part of an editor window for objects, agents, etc. CITI knows nothing about the resource UID, just the type of resource and the CITI UID. 

This should be a "find first and display" action. The catalog controller is meant to display multiple resources while this view is specifically for one resource. 

Let me know how much this will affect the milestone timing. I am open to using your proposed URL initially if that helps.

**Comment by awead** [comment]
Then I'd recommend putting it in a separate controller. This will make it easier to the manage routes. Otherwise, you'd need to have extra logic in the routing to distinguish between `/works/1234` versus `/works/relationships` since "relationships" isn't the id of a work.

I'd also recommend using Rails' customary url parameters, so your above example would be something like: `/relationships?citiUid=<citi_uid>&model=<model>` to which you eventually add different parameters such as legacy uid.

**Comment by scossu** [comment]
That sounds good.
