### ISSUE TITLE
Update Tag when a TagCat is deleted

### ISSUE THREAD

**Issue by awead** [aic-collections/aicdams-lakeshore#52]
If a TagCat is deleted, any Tags that are using that TagCat will need to updated.

**Comment by scossu** [comment]
Having dropped the Tag and TagCat model in favor of the List and ListItem one, this should be reviewed. 
In particular, it is relevant to know in which cases a list needs to be deleted. 
Since a List is tied to a property, the only case I foresee this to happen is if the content model changes and a property is removed or merged with another one. This operation would be manual and at the Fedora level, so a Sufia interaction should not be involved. 
As such, I would rather close this issue unless other use cases come up.
